### ISSUE TITLE
Deploy public SSH keys in managed hosts

### ISSUE THREAD

**Issue by ferrarimarco** [ferrarimarco/home-lab#2]
SSH Keys must be set up to allow SSH access. This should me automatically managed with Ansible.

See:
* https://carlosbuenosvinos.com/github-ansible-deploy-your-public-ssh-keys-to-your-server/
* http://blog.scottlowe.org/2015/05/26/bootstrap-servers-ansible/

Possible implementation:
```
- name: Ensure SSH keys are installed
  authorized_key: user=root key=https://github.com/{{ item }}.keys
  become: yes
  with_items:
    - ferrarimarco
```
